version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ECR_PUBLIC_REGISTRY=public.ecr.aws
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_PUBLIC_REGISTRY
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...      
      - ECR_PUBLIC_REPOSITORY=$ECR_PUBLIC_REGISTRY/sligh-games
      - GODOT_IMAGE_NAME=amplify-godot-engine
      - docker build --build-arg GODOT_VERSION=$GODOT_VERSION -t $GODOT_IMAGE_NAME:$GODOT_VERSION .
      - docker tag $GODOT_IMAGE_NAME:$GODOT_VERSION $ECR_PUBLIC_REPOSITORY/$GODOT_IMAGE_NAME:$GODOT_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_PUBLIC_REPOSITORY/$GODOT_IMAGE_NAME:$GODOT_VERSION